// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.EF;

#nullable disable

namespace Project.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107120000_AddGradingFeaturestoStudentAnswer")]
    partial class AddGradingFeaturestoStudentAnswer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: Simplified snapshot showing StudentAnswer changes
            modelBuilder.Entity("Project.Data.Entities.Exams.StudentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("ImageAnswerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PointsEarned")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentExamResultId")
                        .HasColumnType("int");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradedByUserId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentExamResultId");

                    b.ToTable("StudentAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
